name: Validate-XML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: korelstar/xmllint-problem-matcher@v1
      - name: Setup XMLLint
        run: sudo apt update && sudo apt install --no-install-recommends -y libxml2-utils
      - name: Validate ModLinks.xml
        run: xmllint --noblanks ModLinks.xml --schema Schemas/ModLinks.xml
      - name: Validate APILinks
        run: xmllint --noblanks ApiLinks.xml --schema Schemas/ApiLinks.xml

  verify:
    needs: [build]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup ModLinksShaVerifier
        run: Invoke-WebRequest -Uri "https://github.com/jngo102/ModLinksShaVerifier/releases/download/1.0.0/ModLinksShaVerifier.exe" -OutFile "ModLinksShaVerifier.exe"
      - name: Verify APILinks SHAs
        run: .\ModLinksShaVerifier.exe ApiLinks.xml
      - name: Verify ModLinks.xml SHAs
        run: .\ModLinksShaVerifier.exe ModLinks.xml
